### ISSUE TITLE
EcoTimesScrapper Style Overload

### ISSUE THREAD

**Issue by Khalid-Azmatullah** [Khalid-Azmatullah/AarambhAI#2]
Extracted article data is overloaded with style innerText with removal being challenging due to random nature of this shitty javascript code. Would rather load it up in python or ruby.
Would just any open-source hero to help.

![Screenshot 2024-11-03 224653](https://github.com/user-attachments/assets/36dd89bd-101b-43d1-a4f6-95c0e9a58ece)
This shitty loop is not completing all the replacements.

articleStyleTrashPerfected is an array of style innerText with minimal inaccuracy.
articleDivFree is a string with article data stuffed with style innerText.

I have tried 7 different methods and yet this piece of shit refuses to work.

**Comment by Khalid-Azmatullah** [comment]
Make this thing work ASAP. Find the issue and nip it in it's bud. The more I spend time on it, the more I go mad. HELP

**Comment by Mr-Codes-cant-code** [comment]
This is getting painstakingly harder to debug each day.

https://github.com/user-attachments/assets/e853ce39-3ed1-4239-ba16-dd62b647b22a

I would rather spend my time on the AI than this stupid piece of code. Today I shall try to debug this completely and if I am unsuccessful I shall transfer this task  to Ruby which has much better predictably.

![IMG20241101150010.jpg](https://github.com/user-attachments/assets/c54dbfe5-a993-473e-98d0-1c80b985c2e4)

**Comment by Khalid-Azmatullah** [comment]
**Made some Progress today. However this piece of garbage started another issue.**

I am going to transfer this task to Ruby 😔. 
Life 🧬 just sucks sometimes and this is probably one of those times.

🤬🤬👿

**Comment by Mr-Codes-cant-code** [comment]
Ruby for life ♦️

**Comment by Mr-Codes-cant-code** [comment]
_____________________
    /           /              \          \
  /           /                  \          \
/______ /____________\______\ 
\            \                    /           /
  \           |                   |           /
    \         \                 /          /
      \        |                |          /
        \       \             /         /
          \       |           |         /
            \      \        /        /
              \      |      |        /
                \    |      |      /
                  \_ |___|__/

**Comment by Harman851997** [comment]
Man calm down

**Comment by Khalid-Azmatullah** [comment]
**🚨⚠️ URGENT ISSUE NEED TO BE IMMEDIATELY**

**Comment by Harman851997** [comment]
What happened

**Comment by Khalid-Azmatullah** [comment]
🎉🎉🎉 **Issue Resolved** 🎉🎉🎉
FINALLY!! I got the issue to stop and get that pristine and mouth watering article data. The issue had something to do with the unpredictability of JavaScript (or I am too dumb to understand how it works) but anyways, ruby came to the rescue and did the impossible by finishing the job in the most stylish way possible.

Anyways one problem still remains that is, the data is not formatted perfectly. I will open an issue about it but there is no need to address it now.
