### ISSUE TITLE
EcoTimes + Toi Article Data Formatting Issue

### ISSUE THREAD

**Issue by Khalid-Azmatullah** [Khalid-Azmatullah/AarambhAI#3]
**NOT URGENT**
This issue is opened with respect to the formatting issue faced when pushing the data into JSON Files
Like the one given below:

![Screenshot 2024-11-06 215203](https://github.com/user-attachments/assets/742f8b5f-3cf1-48b2-8568-ab880d099e08)

This is not at all urgent and I just to handle it with Ruby or Python.

**Comment by Khalid-Azmatullah** [comment]
This Issue is for beginners.

**Comment by Mr-Codes-cant-code** [comment]
Change of plans, I will do it today.

**Comment by Mr-Codes-cant-code** [comment]
> This Issue is for beginners.

Yeah, for sure. Let's just do it today.

**Comment by Khalid-Azmatullah** [comment]
** This issue was too easy**
